// <auto-generated />
using LearningApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LearningApp.API.Migrations
{
    [DbContext(typeof(LearningAppContext))]
    [Migration("20180623203046_v123")]
    partial class v123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LearningApp.Core.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<double>("Device_Id");

                    b.Property<double>("Person_Id");

                    b.HasKey("Id");

                    b.ToTable("Incident");
                });

            modelBuilder.Entity("LearningApp.Core.Entities.Measures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Image")
                        .IsRequired();

                    b.Property<int>("Index");

                    b.Property<string>("MeasureType")
                        .IsRequired();

                    b.Property<string>("Police_Station");

                    b.HasKey("Id");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("LearningApp.Core.Entities.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Activate_Date");

                    b.Property<string>("Address");

                    b.Property<double>("Device_Id");

                    b.Property<string>("Device_Number");

                    b.Property<decimal>("Latitude");

                    b.Property<decimal>("Longitude");

                    b.Property<double>("Person_Id");

                    b.Property<string>("Police_Station");

                    b.HasKey("Id");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
