// <auto-generated />
using LearningApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LearningApp.API.Migrations
{
    [DbContext(typeof(LearningAppContext))]
    [Migration("20180618134559_v100")]
    partial class v100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LearningApp.Core.Entities.Incidentx", b =>
                {
                    b.Property<DateTime>("Id");

                    b.Property<DateTime>("Date");

                    b.Property<float>("Device_Id");

                    b.Property<float>("Person_Id");

                    b.HasKey("Id");

                    b.ToTable("Incidentx");
                });
#pragma warning restore 612, 618
        }
    }
}
